### PR TITLE
add upsert alias for store.save()

### PR DESCRIPTION
**Pull request by dzhelezov**

### CODE REVIEW

**Comment by belopash** [comment]
Why do we need this?

**Comment by dzhelezov** [comment]
At least two devs were using `save()` + `insert()`. So the name `save()` seems to be misleading, `upsert()` is more accurate.

**Comment by belopash** [comment]
Hmm, maybe it's better to make "save" an alias instead? It will just be more logical

**Comment by dzhelezov** [comment]
I am neutral with respect to that, let @eldargab decide and merge :)

**Comment by eldargab** [comment]
Yes, it's better for `.save()` to be an alias. Because that way its meaning will become easier to discover:

1. jump to definition
2. immediately see, that `.save() == .upsert()`.

Versus

1. jump to definition
2. read a long description text

**Pull request merged**
