### PR TITLE
Make OneToOne releations bi-directional

### PR DESCRIPTION
**Pull request by belopash**

### CODE REVIEW

**Comment by eldargab** [comment]
What is the case which bothered you enough to make a PR? :)

**Comment by belopash** [comment]
@eldargab missed the comment

```
type Account @entity {
    id: ID!
    publicKey: ID! @index
    stashOf: Staker @derivedFrom(field: "stash")
    controllerOf: Staker @derivedFrom(field: "controller")
}

type Staker @entity {
    id: ID!
    stash: Account! @unique
    controller: Account @unique

    ...
}
```
need to query account in code to get staker entity

**Comment by belopash** [comment]
for now I patched it locally, so it's not urgent

**Comment by prap1546** [comment]
good

**Pull request merged**
