### PR TITLE
Rename MessageEnqueued event to MessageQueued

### PR DESCRIPTION
**Pull request by osipov-mit**

### CODE REVIEW

**Comment by dzhelezov** [comment]
We need to test agains ArrowSquid for Gear

**Comment by eldargab** [comment]
Hey, @osipov-mit , is it for the whole mainnet or there are blocks with old names?

**Comment by osipov-mit** [comment]
> Hey, @osipov-mit , is it for the whole mainnet or there are blocks with old names?

Yes it is for the whole mainnet

**Comment by dzhelezov** [comment]
@abernatskiy we should update https://docs.subsquid.io/substrate-indexing/specialized/gear/ too

**Comment by eldargab** [comment]
But after actual release

**Pull request merged**
